# Generated by Django 5.0.7 on 2025-06-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlInventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
