# Generated by Django 5.0.7 on 2025-06-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlInventario', '0002_alter_producto_descripcion_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='autorizado',
            field=models.BooleanField(default=False),
        ),
    ]
