# Generated by Django 5.0.7 on 2025-06-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlInventario', '0003_pedido_autorizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
