# Generated by Django 5.0.7 on 2025-09-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlInventario', '0004_pedido_motivo_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='autorizado',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
