# Generated by Django 4.2.30 on 2026-08-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlInventario', '0005_alter_pedido_autorizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='motivo_pedido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
